'mode' argument can now take dates. Refers to archived versions of Wordbank.
langcog/wordbankr pull request #18
Opened 2018-03-22 23:27 UTC by daniellekellier

2018-04-23 18:17 UTC, mikabr requested changes
generally looks great! apart from inline comments, a few overall thoughts:
- one high-level issue is that `wordbankr` functions refer to specific column names, which can change between versions of the database – it needs to be clear to users that they need to note both which version of `wordbankr` they're using and which version of the database they're using, otherwise they can be inconsistent and cause reproducibility problems
- would be good to add versioning usage information to the vignette
- would be good to run `lintr::lint_package()` and fix style issues

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +    db_info["address"] <- "wordbank-backup.canyiscnpddk.us-west-2.rds.amazonaws.com"
might this address change? if so we should fetch it from somewhere stable rather than hardcoding it into the package

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +                          warning = function(e) {
I think it would be better if this threw an error out instead of showing messages and retrieving the latest version.

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +    if (!grepl('Decimal', w)) {message(conditionMessage(w))}
shouldn't this throw the warning instead of showing a message?

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +                            message("Please enter dates as in 'Ymd' or 'mdY' format.")
this is confusing to the user because the dates can actually be in a lot of different format as long as they're in that order

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +        dplyr::filter(.data$date_archived <= mode_date) %>%
it should be clearer that the date supplied doesn't have to be exact and that what's retrieved is the latest version that's before or on that date – maybe explain that in the documentation and show a message with exactly with version ends up being retrieved

2018-04-23 18:17 UTC, mikabr commented on R/wordbankr.R
> +#' @param mode A string indicating connection mode: one of \code{"local"},
these param docs can be inherited from `find_database()`

2018-05-04 19:19 UTC, daniellekellier commented on R/wordbankr.R
> +    db_info["address"] <- "wordbank-backup.canyiscnpddk.us-west-2.rds.amazonaws.com"
The address shouldn't change! Did you want a prettier endpoint URL though?

2018-05-04 19:21 UTC, daniellekellier commented on R/wordbankr.R
> +                            message("Please enter dates as in 'Ymd' or 'mdY' format.")
Is there a better way to describe that the delimiters themselves don't matter as much?

2018-05-04 19:48 UTC, daniellekellier commented on R/wordbankr.R
> +                          warning = function(e) {
lubridate throws out a warning instead of an error when it fails to parse a message. I can use assertthat to throw an error though

2018-05-04 20:39 UTC, daniellekellier commented
I get this error from Travis:
The command "sudo apt-get install -y r-cran-dplyr r-cran-tidyr r-cran-knitr" failed and exited with 100 during .

Any ideas on how to fix this?

2018-05-04 23:46 UTC, mikabr commented
@daniellekellier this could be because travis switching to R 3.5, which messes up the package cache – try deleting existing caches (under "more options" on the right in the build page)

2022-08-12 02:02 UTC, closed without merging